theme: jekyll-theme-minimal
logo: media/SciencesPoLogo.png
description: "2020 Winter School on Reims Campus - Thomas Tari[mailto:thomas.tari@sciencespo.fr], médialab and Forccast"
title: "Science and Society"
